### ISSUE TITLE
Don't list products with no files in [downloads_history]

### ISSUE THREAD

**Issue by dgoldak** [easydigitaldownloads/edd-downloads-as-services#15]
Since we don't list Downloads in the receipt and order confirmation page, that logic should also apply to [downloads_history]. Requesting we don't list products in [downloads_history] shortcode that contain no download files. For example the Pay Your Invoice product should not exist.

<img width="712" alt="Screen Shot 2021-02-17 at 11 11 21 AM" src="https://user-images.githubusercontent.com/30910807/108541397-06421b80-72a8-11eb-9cc8-a927af50f791.png">

Related to this issue: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6448#issuecomment-780710811

**Comment by robincornett** [comment]
I'm going to close this as it can be resolved by using the new "User Downloads" block instead of the download history shortcode.
