### ISSUE TITLE
Adding extra dash to product name output

### ISSUE THREAD

**Issue by SeanChDavis** [easydigitaldownloads/edd-downloads-as-services#3]
Seems to be happening on the `[download_history]` shortcode as well as in the email receipt. 

<img width="768" alt="screenshot 2017-02-20 12 55 03" src="https://cloud.githubusercontent.com/assets/2359131/23141477/d9f88b4c-f76b-11e6-9d4d-cfb6972c7176.png">

<img width="499" alt="screenshot 2017-02-20 12 55 40" src="https://cloud.githubusercontent.com/assets/2359131/23141487/e5f8b11a-f76b-11e6-95fe-a9762eb1d601.png">

**Comment by amdrew** [comment]
@SDavisMedia 

The hyphen in the email seems to be EDD core, I can replicate it without DAS installed and for normal downloads (non-service). Can you try again without DAS activated to confirm?

I can't replicate the hyphen with the [download_history] shortcode. This is what I see:

<img width="639" alt="screen shot 2017-03-09 at 1 04 30 pm" src="https://cloud.githubusercontent.com/assets/52581/23729829/f64639ec-04c8-11e7-8e61-c5f88cb3ad27.png">

Does it happen without DAS? Latest version of EDD and DAS?

**Comment by mindctrl** [comment]
@sumobi this? https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5504

**Comment by SeanChDavis** [comment]
that ^^^ :+1: 

You can close this. Sorry... forgot I even opened this issue before realizing what it was. #redherring

**Comment by amdrew** [comment]
like magic, thanks gents
