### ISSUE TITLE
Email purchase receipt shows `No downloadable files found.` 

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/edd-downloads-as-services#4]
Email purchase receipts are now showing `No downloadable files found.` since the latest EDD update.

Comes from this change:
https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5501/files

Will put together a PR that simply filters the text to nothing if it is a service without a file.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by amdrew** [comment]
PR https://github.com/easydigitaldownloads/edd-downloads-as-services/issues/5

@easydigitaldownloads/core-devs Ready for testing (If anyone wants to test apart from myself).

**Comment by amdrew** [comment]
Merged, closing
