### ISSUE TITLE
Add Danish translation

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/edd-downloads-as-services#6]
We got a community contributed translation. PR coming.

**Comment by dgoldak** [comment]
@cklosowski I just noticed this issue. Is this something we should still have open? I didn't think we add specific translations to extensions so I'm not sure this one would be any different. But maybe I'm missing something.

**Comment by cklosowski** [comment]
We do when we have them, I'll have to test to make sure it still works.
